#Hostname
resource "fortios_system_global" "hostname" {
  hostname  = "FortiDEMO_AWS"
}

#System > Interface > port1
resource "fortios_system_interface" "interfaces" {
  name         = "port1"
  vdom         = "root"
  mode         = "dhcp"
  allowaccess  = "ping https ssh fgfm"
  description  = "Created by Terraform Provider for FortiOS"
  autogenerated = "auto"
}

#System > Interface > port2
resource "fortios_system_interface" "port2" {
  name                    = "port2"
  vdom                    = "root"
  mode                    = "dhcp"
  allowaccess             = "ping ssh"
  description             = "Created by Terraform Provider for FortiOS"
  defaultgw               = "disable"
  device_identification   = "enable"
  scan_botnet_connections = "enable"
  autogenerated = "auto"
 }

#Firewall Policies (3)
resource "fortios_firewall_policy" "policy3" {
  policyid = 105
  name = "UbuntuEgress"
  action = "accept"
  nat = "enable"
  schedule = "always"
  utm_status = "enable"
  fixedport = "enable"
  fsso = "disable"
  av_profile = "default"
  ssl_ssh_profile = "certificate-inspection"

  srcintf {
    name = "port2"
  }

  dstintf {
    name = "port1"
  }

  srcaddr {
    name = "all"
  }

  dstaddr {
    name = "all"
  }

  service {
    name = "ALL"
  }
}

#VPN Certificate Remote(Needs Base64encode)
resource "fortios_vpncertificate_remote" "TEMP_Cert_1" {
  name = "TEMP_Cert_2"
  #remote = file("${path.module}/TEMP_Cert_1.pem")
  remote = "-----BEGIN CERTIFICATE-----\nMIIE4jCCA8qgAwIBAgIDB1LKMA0GCSqGSIb3DQEBCwUAMIGrMQswCQYDVQQGEwJV\nUzETMBEGA1UECBMKQ2FsaWZvcm5pYTESMBAGA1UEBxMJU3Vubnl2YWxlMREwDwYD\nVQQKEwhGb3J0aW5ldDEeMBwGA1UECxMVQ2VydGlmaWNhdGUgQXV0aG9yaXR5MRsw\nGQYDVQQDExJmb3J0aW5ldC1zdWJjYTIwMDExIzAhBgkqhkiG9w0BCQEWFHN1cHBv\ncnRAZm9ydGluZXQuY29tMCAXDTE5MDgxNjIyMzk0MloYDzIwNTYwMTE5MDMxNDA3\nWjCBnTELMAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExEjAQBgNVBAcT\nCVN1bm55dmFsZTERMA8GA1UEChMIRm9ydGluZXQxEjAQBgNVBAsTCUZvcnRpR2F0\nZTEZMBcGA1UEAxMQRkdWTTAxVE0xOTAwNDQ1MjEjMCEGCSqGSIb3DQEJARYUc3Vw\ncG9ydEBmb3J0aW5ldC5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB\nAQCsBElTBuEXPSHysZFEAhfjTmzCV6cHAng92A74NVnNw7nPJ4ePPWxxIw9KbOIE\n+fqGC53nMH9UGKGdDyXTV7DbC1TZDB0GvQUalxdpFTfAUaMz/FeQelrn7vxkGDU+\n6hX8NlJcl0aPb8lQTg5S31ItlFoArPbR9G5tFB/JpdzM+pTZGWiTA7NGO2DyYH3U\nkvlK8MPMmGlvdsitnE0WNuDTxAh1M5EY9fOx97TaKN/e4Kx6p3uDfLUVm2sjzCgW\nr121SEW5+R1SOEI1V7Vq7EdWWxn3nNQQvs0f+PlwkmyM4CeB2i2AMd7uVeSNxJG5\n5fpbBHr2sNVLqKFWeOG5fgM9AgMBAAGjggEXMIIBEzAdBgNVHQ4EFgQUWOs88eNM\nyGqCZW79makXO1DL3mEwgdMGA1UdIwSByzCByIAUmCslPDDKLCtW59v8WTOz3D1b\natehgaukgagwgaUxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRIw\nEAYDVQQHEwlTdW5ueXZhbGUxETAPBgNVBAoTCEZvcnRpbmV0MR4wHAYDVQQLExVD\nZXJ0aWZpY2F0ZSBBdXRob3JpdHkxFTATBgNVBAMTDGZvcnRpbmV0LWNhMjEjMCEG\nCSqGSIb3DQEJARYUc3VwcG9ydEBmb3J0aW5ldC5jb22CAiABMAwGA1UdEwEB/wQC\nMAAwDgYDVR0PAQH/BAQDAgeAMA0GCSqGSIb3DQEBCwUAA4IBAQCLCTiImQqJfCGt\njqUJVNSRz/V/pUi6ASOMWIZ4GL8RwFy/M/hi237hiOq7rOTQtSf+sorOGS1f+Y0s\nTa+g1aR4nMK7hJHLrvhFP/j2nn/TDEE1oGWkUk41RFE6XmEnF+0O+CJSxSQk75Kf\nGMw4HbZbpTtcXKEhh+U5CJDYHksJl3+oibppPNUWoIZ3b8qW1BRHC6amrB8ngbnq\n5TlLLAgd59GzaeqJ0Zv0/GVc5fVT4Va5Gmz4TNiZYScbJgOcO4HnjydN4QedVtQH\nzn6djXEePkk5tfN9Bn49JzDTJInJaEOM1MbOf2gyDtZTzcDnby/jpm+JUgVq1oBv\ncp0ya7gs\n-----END CERTIFICATE-----"
}

#SDN Connector
resource "fortios_system_sdnconnector" "awsSdn" {
  name = "awsSDN"
  status = "enable"
  type = "aws"
  use_metadata_iam = "enable"
}